server {
    listen 19081;
    server_name _;
    root /usr/share/nginx/html;

    location = / { return 302 /listen.html; }

    location ~* \.html$ { add_header Cache-Control "no-store"; expires 0; }
    location ~* \.(js|css|png|jpg|ttf|woff2)$ { expires 1h; access_log off; }

    location /ws {
        proxy_pass         http://ts_api:8000/ws;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_read_timeout 86400s;
    }

    location /api/ {
        proxy_pass         http://ts_api:8000/api/;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_http_version 1.1;
    }

    location / { try_files $uri $uri/ /listen.html; }
}
