server {
    listen 19000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.html$ { add_header Cache-Control "no-store"; expires 0; }
    location ~* \.(js|css|png|jpg|ico|woff2|svg|webp|ttf)$ { expires 1h; access_log off; }
    location /fonts/ { try_files $uri =404; expires 7d; add_header Access-Control-Allow-Origin "*"; }
    location /img/   { try_files $uri =404; expires 7d; }
    location /css/   { try_files $uri =404; }
    location /js/    { try_files $uri =404; }

    location /livekit/ {
        proxy_pass         http://ts_api:8000/api/v1/livekit/;
        proxy_set_header   Host $host;
        proxy_http_version 1.1;
    }

    location /ws {
        proxy_pass         http://ts_api:8000/ws;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location /api/ {
        proxy_pass         http://ts_api:8000/api/;
        proxy_set_header   Host       $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_read_timeout 300;
    }

    location = / {
        try_files /index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
