listening-port=3478
fingerprint
use-auth-secret
static-auth-secret=SecureSecret2026TurnKey32Chars!!
realm=translation.local
total-quota=100
no-loopback-peers
no-multicast-peers
external-ip=10.170.116.132
log-file=/var/log/turnserver.log
simple-log
no-cli
no-tls
no-dtls
