port: 7880
log_level: info

rtc:
  tcp_port: 7881
  port_range_start: 55000
  port_range_end: 55100
  use_external_ip: false
  node_ip: 192.168.0.15

redis:
  address: ts_redis:6379
  password: vitnap@ssw0rd

keys:
  translation_api: SecureSecret2026LiveKitKey32Chars!!

room:
  auto_create: true
  empty_timeout: 300
  max_participants: 500

turn:
  enabled: false

webhook:
  api_key: translation_api
  urls:
    - http://ts_api:8000/api/v1/webhooks/livekit

logging:
  pion_level: error
